spring:
  profiles:
    active: dev
sabercon:
  default-password: ENC(dEJKRMTx4Z+iYr9fncOkqs11FpfRP57QoPPu5KJc6pyNTsVQmDTpNjtLIAoMLBGv)
  jwt-key: ENC(kp1z3QCvCnvNVjonJjW0Kr0P23XHXSEH1CuAuL8qZBSv05wehp5CMjuuo0pRBEyU)
