server:
  port: 8080
spring:
  data:
    mongodb:
      host: www.sabercon.cn
      port: 27017
      database: mogumin
      username: root
      password: ${sabercon.default-password}
      authentication-database: admin
  redis:
    host: www.sabercon.cn
    port: 6379
