server:
  port: 8080
spring:
  data:
    mongodb:
      database: mogumin
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    web: debug
    sql: debug
    cn.sabercon: debug
