jasypt.encryptor.password: '<password>'
server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:postgresql://root:root@localhost:5432/megumin
  data:
    mongodb:
      database: megumin
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    web: debug
    org.springframework.r2dbc: debug
    org.springframework.data.mongodb: debug
    cn.sabercon: debug
debug: true
