version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /root/docker/mongo/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DEFAULT_PASSWORD}
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${DEFAULT_PASSWORD}
    ports:
      - 6379:6379
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /root/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/docker/nginx/html:/usr/share/nginx/html
      - /root/docker/nginx/log:/var/log/nginx
    ports:
      - 80:80
  mogumin:
    image: ghcr.io/sabercon/mogumin
    container_name: mogumin
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JASYPT_ENCRYPTOR_PASSWORD: ${KEY}
    depends_on:
      - mongo
      - redis
