version: '3'

services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=megumin
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
    