# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Docker

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish with Jib
        # Jib cannot handle the image name correctly because my account contains uppercase letters
        # So I write the image name hard-coded
        run: ./gradlew jib -Djib.to.image="${{ env.REGISTRY }}/sabercon/megumin:latest" \
          -Djib.to.auth.username="${{ github.actor }}" \
          -Djib.to.auth.password="${{ secrets.GITHUB_TOKEN }}"
